UsersShared.create!([
  {owner_id: 1, shared_id: 2, state: "P"},
  {owner_id: 1, shared_id: 5, state: "P"}
])
# User.create!([
#   {name: "Matheus", email: nil, password: nil, activation_code: nil, state: "P"},
#   {name: "Matheus Dois", email: "fulana@gmail.com", password: nil, activation_code: nil, state: "P"},
#   {name: "Marvella Harris", email: "cicrano@gmail.com", password: nil, activation_code: nil, state: "P"},
#   {name: "Glenn Kovacek", email: "norman@kub.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Reginald Welch V", email: "flavia.kris@schroeder.io", password: nil, activation_code: nil, state: "P"},
#   {name: "Prof. Lincoln DuBuque", email: "avery_kutch@mohr-nolan.co", password: nil, activation_code: nil, state: "P"},
#   {name: "Margarito Bradtke", email: "sadie@walsh.org", password: nil, activation_code: nil, state: "P"},
#   {name: "Ngoc Toy", email: "antonia.rosenbaum@reynolds.info", password: nil, activation_code: nil, state: "P"},
#   {name: "Hollis Hoppe", email: "clarissa_wunsch@sanford.net", password: nil, activation_code: nil, state: "P"},
#   {name: "Janell Wiegand", email: "ryan@prosacco.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Shizuko Douglas", email: "norma_hettinger@brown.co", password: nil, activation_code: nil, state: "P"},
#   {name: "Sherly Rowe MD", email: "donald.reynolds@hammes.biz", password: nil, activation_code: nil, state: "P"},
#   {name: "Rep. Jame Von", email: "billy_torphy@kozey-keebler.biz", password: nil, activation_code: nil, state: "P"},
#   {name: "Ellen Heller CPA", email: "felton@effertz.net", password: nil, activation_code: nil, state: "P"},
#   {name: "Francoise Heathcote", email: "willy.hegmann@weimann.com", password: nil, activation_code: nil, state: "P"},
#   {name: "Beata Kling", email: "christoper.bradtke@ankunding-gerhold.org", password: nil, activation_code: nil, state: "P"},
#   {name: "Dustin Lemke", email: "barney.cronin@farrell.info", password: nil, activation_code: nil, state: "P"},
#   {name: "Demarcus D'Amore", email: "selene.ward@emmerich.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Jade Johnson", email: "digna.denesik@king-kreiger.info", password: nil, activation_code: nil, state: "P"},
#   {name: "Alena Smitham", email: "charlette@klocko-ohara.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Jalisa Hermann", email: "shelton.bednar@zieme.org", password: nil, activation_code: nil, state: "P"},
#   {name: "Cecil Schuster", email: "lucius.huel@blick-muller.biz", password: nil, activation_code: nil, state: "P"},
#   {name: "Valene Quigley CPA", email: "muriel@mckenzie.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Raphael Carroll IV", email: "margeret@gutmann.com", password: nil, activation_code: nil, state: "P"},
#   {name: "Lyman Herman", email: "emmaline@vonrueden.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Gidget Pacocha", email: "hee.casper@runte.info", password: nil, activation_code: nil, state: "P"},
#   {name: "Laurice Kessler", email: "eliseo@ohara.io", password: nil, activation_code: nil, state: "P"},
#   {name: "Tyron Spinka", email: "pat@jakubowski-hand.biz", password: nil, activation_code: nil, state: "P"},
#   {name: "Fr. Sharda Baumbach", email: "ellamae@barton.net", password: nil, activation_code: nil, state: "P"},
#   {name: "Oswaldo Schmitt", email: "kandi@huels.net", password: nil, activation_code: nil, state: "P"},
#   {name: "Cedric Kuhlman", email: "fanny@dach-greenfelder.org", password: nil, activation_code: nil, state: "P"},
#   {name: "Anglea Satterfield", email: "bud_hahn@klein.org", password: nil, activation_code: nil, state: "P"},
#   {name: "Stevie Nolan II", email: "roman_wehner@barton-fahey.info", password: nil, activation_code: nil, state: "P"},
#   {name: "Janiece Wisoky", email: "lecia@rippin-breitenberg.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Sudie McGlynn", email: "narcisa@schinner.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Rosamond Heidenreich", email: "shanika_johns@hettinger.co", password: nil, activation_code: nil, state: "P"},
#   {name: "Dr. Carmen Hoeger", email: "tyron@torphy.io", password: nil, activation_code: nil, state: "P"},
#   {name: "Rev. Bernard Yundt", email: "clint.damore@koch.name", password: nil, activation_code: nil, state: "P"},
#   {name: "Amb. Lemuel Hyatt", email: "lila@johnston.com", password: nil, activation_code: nil, state: "P"},
#   {name: "Williams Renner MD", email: "tomika.roberts@bosco.biz", password: nil, activation_code: nil, state: "P"},
#   {name: "Myung Ritchie DDS", email: "jordan@kuhic.co", password: nil, activation_code: nil, state: "P"},
#   {name: "The Hon. Eugenio Koch", email: "lakendra@oconner.io", password: nil, activation_code: nil, state: "P"}
# ])
